"""Install Grok Build global PreToolUse wrapper (box 2).

Writes a customized wrapper (absolute python + package root so the hook works
even when grok's PATH lacks cosmic-cli) into ~/.cosmic-cli/hooks/ and a global
~/.grok/hooks/cosmic-pretooluse.json pointing at it.
"""

from __future__ import annotations

import os
import shutil
import stat
import sys
from pathlib import Path
from typing import Tuple

_PKG_ROOT = Path(__file__).resolve().parent.parent
_WRAPPER_SRC = _PKG_ROOT / "scripts" / "hooks" / "cosmic-gate-wrapper.sh"
_TEMPLATE_SRC = _PKG_ROOT / "scripts" / "hooks" / "cosmic-pretooluse.json.template"
_LAUNCHER_SRC = _PKG_ROOT / "scripts" / "cosmic-launch-grok.sh"


def _render_wrapper() -> str:
    """Embed absolute paths so PreToolUse hooks don't depend on PATH."""
    py = sys.executable
    root = str(_PKG_ROOT)
    return f"""#!/usr/bin/env bash
# Auto-generated by cosmic-cli init --grok — do not edit by hand.
# Regenerated on next init --grok --force.
set -euo pipefail

COSMIC_PY={py!r}
COSMIC_ROOT={root!r}
export PYTHONPATH="${{COSMIC_ROOT}}${{PYTHONPATH:+:$PYTHONPATH}}"

_cosmic() {{
  "${{COSMIC_PY}}" -m cosmic_cli.main "$@"
}}

_deny() {{
  local reason="${{1:-cosmic gate: denied}}"
  python3 -c 'import json,sys; print(json.dumps({{"decision":"deny","reason":sys.argv[1]}}))' "$reason"
  exit 2
}}

_allow() {{
  printf '%s\\n' '{{"decision":"allow"}}'
  exit 0
}}

if ! _cosmic gate --verb-check >/dev/null 2>&1; then
  _deny "cosmic-cli gate --verb-check failed (missing or broken)"
fi

if command -v openssl >/dev/null 2>&1; then
  NONCE="$(openssl rand -hex 16)"
else
  NONCE="$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
fi
export COSMIC_GATE_NONCE="${{NONCE}}"

# Operator approval channel (Mode B): grok-build may not pass arbitrary env
# into hook processes. Prefer COSMIC_APPROVAL_TOKEN if set; else one-shot file
# written by `cosmic-cli helix accept-pause` (0600, deleted after successful claim).
if [[ -z "${{COSMIC_APPROVAL_TOKEN:-}}" && -f "${{HOME}}/.cosmic-cli/operator_approval_token" ]]; then
  export COSMIC_APPROVAL_TOKEN="$(tr -d '[:space:]' < "${{HOME}}/.cosmic-cli/operator_approval_token")"
fi

INPUT="$(cat)"

set +e
OUT="$(printf '%s' "${{INPUT}}" | COSMIC_GATE_NONCE="${{NONCE}}" env COSMIC_APPROVAL_TOKEN="${{COSMIC_APPROVAL_TOKEN:-}}" _cosmic gate --hook grok --mode safe 2>/dev/null)"
set -e

EXPECTED="COSMIC-ALLOW v1 ${{NONCE}}"
if [[ "${{OUT}}" == "${{EXPECTED}}" || "${{OUT}}" == "${{EXPECTED}}"$'\\n' ]]; then
  _allow
fi

_deny "cosmic gate: no valid COSMIC-ALLOW sentinel"
"""


def install_grok_hooks(*, force: bool = False) -> Tuple[str, bool]:
    if not _TEMPLATE_SRC.is_file():
        return f"[Error] hook template missing at {_TEMPLATE_SRC}", False

    dest_dir = Path.home() / ".cosmic-cli" / "hooks"
    dest_dir.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(dest_dir, 0o700)
    except OSError:
        pass

    wrapper_dst = dest_dir / "cosmic-gate-wrapper.sh"
    wrapper_dst.write_text(_render_wrapper(), encoding="utf-8")
    wrapper_dst.chmod(wrapper_dst.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # Keep stock template wrapper alongside for repo reference
    if _WRAPPER_SRC.is_file():
        stock = dest_dir / "cosmic-gate-wrapper.stock.sh"
        shutil.copy2(_WRAPPER_SRC, stock)

    if _LAUNCHER_SRC.is_file():
        launcher_dst = dest_dir / "cosmic-launch-grok.sh"
        # Rewrite launcher to use embedded cosmic
        py = sys.executable
        root = str(_PKG_ROOT)
        launcher_dst.write_text(
            f"""#!/usr/bin/env bash
set -euo pipefail
export PYTHONPATH={root!r}${{PYTHONPATH:+:$PYTHONPATH}}
COSMIC_PY={py!r}
_cosmic() {{ "${{COSMIC_PY}}" -m cosmic_cli.main "$@"; }}
echo "cosmic-launch-grok: running boot canary…" >&2
if ! _cosmic gate --boot-canary; then
  echo "cosmic-launch-grok: BOOT CANARY FAILED — refuse cockpit launch" >&2
  exit 1
fi
if ! command -v grok >/dev/null 2>&1; then
  [[ -x "${{HOME}}/.grok/bin/grok" ]] && PATH="${{HOME}}/.grok/bin:${{PATH}}"
fi
if ! command -v grok >/dev/null 2>&1; then
  echo "cosmic-launch-grok: grok not on PATH" >&2
  exit 1
fi
echo "cosmic-launch-grok: canary PASS — exec grok" >&2
exec grok "$@"
""",
            encoding="utf-8",
        )
        launcher_dst.chmod(launcher_dst.stat().st_mode | stat.S_IXUSR)

    grok_hooks = Path.home() / ".grok" / "hooks"
    grok_hooks.mkdir(parents=True, exist_ok=True)
    json_path = grok_hooks / "cosmic-pretooluse.json"
    if json_path.exists() and not force:
        return (
            f"init --grok: wrapper at {wrapper_dst}; hook JSON exists "
            f"({json_path}) — use --force to overwrite",
            True,
        )

    template = _TEMPLATE_SRC.read_text(encoding="utf-8")
    body = template.replace("__WRAPPER_PATH__", str(wrapper_dst.resolve()))
    json_path.write_text(body, encoding="utf-8")

    return (
        f"init --grok ok: wrapper={wrapper_dst} hook={json_path} "
        f"(global PreToolUse). Launch: {dest_dir / 'cosmic-launch-grok.sh'}",
        True,
    )
