"""Install Grok Build global PreToolUse wrapper + temple floor (box 2 + ranking).

Writes:
  - customized wrapper into ~/.cosmic-cli/hooks/
  - global ~/.grok/hooks/cosmic-pretooluse.json
  - temple sandbox profile + default in ~/.grok/sandbox.toml + config.toml
  - launcher that runs boot canary + floor canary, then execs grok under temple
"""

from __future__ import annotations

import os
import shutil
import stat
import sys
from pathlib import Path
from typing import Tuple

_PKG_ROOT = Path(__file__).resolve().parent.parent
_WRAPPER_SRC = _PKG_ROOT / "scripts" / "hooks" / "cosmic-gate-wrapper.sh"
_TEMPLATE_SRC = _PKG_ROOT / "scripts" / "hooks" / "cosmic-pretooluse.json.template"
_LAUNCHER_SRC = _PKG_ROOT / "scripts" / "cosmic-launch-grok.sh"


def _render_wrapper() -> str:
    """Embed absolute paths so PreToolUse hooks don't depend on PATH."""
    py = sys.executable
    root = str(_PKG_ROOT)
    return f"""#!/usr/bin/env bash
# Auto-generated by cosmic-cli init --grok — do not edit by hand.
# Regenerated on next init --grok --force.
set -euo pipefail

COSMIC_PY={py!r}
COSMIC_ROOT={root!r}
export PYTHONPATH="${{COSMIC_ROOT}}${{PYTHONPATH:+:$PYTHONPATH}}"

_cosmic() {{
  "${{COSMIC_PY}}" -m cosmic_cli.main "$@"
}}

_deny() {{
  local reason="${{1:-cosmic gate: denied}}"
  python3 -c 'import json,sys; print(json.dumps({{"decision":"deny","reason":sys.argv[1]}}))' "$reason"
  exit 2
}}

_allow() {{
  printf '%s\\n' '{{"decision":"allow"}}'
  exit 0
}}

if ! _cosmic gate --verb-check >/dev/null 2>&1; then
  _deny "cosmic-cli gate --verb-check failed (missing or broken)"
fi

if command -v openssl >/dev/null 2>&1; then
  NONCE="$(openssl rand -hex 16)"
else
  NONCE="$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
fi
export COSMIC_GATE_NONCE="${{NONCE}}"

# Operator approval channel (Mode B): L2-staged file or exported env.
# Prefer COSMIC_APPROVAL_TOKEN if set; else one-shot file from helix accept-pause.
if [[ -z "${{COSMIC_APPROVAL_TOKEN:-}}" && -f "${{HOME}}/.cosmic-cli/operator_approval_token" ]]; then
  export COSMIC_APPROVAL_TOKEN="$(tr -d '[:space:]' < "${{HOME}}/.cosmic-cli/operator_approval_token")"
fi

INPUT="$(cat)"

set +e
# Bash prefix assignment (NOT `env ... _cosmic`) — `_cosmic` is a shell function.
OUT="$(printf '%s' "${{INPUT}}" | COSMIC_GATE_NONCE="${{NONCE}}" COSMIC_APPROVAL_TOKEN="${{COSMIC_APPROVAL_TOKEN:-}}" _cosmic gate --hook grok --mode safe 2>/dev/null)"
set -e

EXPECTED="COSMIC-ALLOW v1 ${{NONCE}}"
if [[ "${{OUT}}" == "${{EXPECTED}}" || "${{OUT}}" == "${{EXPECTED}}"$'\\n' ]]; then
  _allow
fi

_deny "cosmic gate: no valid COSMIC-ALLOW sentinel"
"""


def _render_launcher(py: str, root: str) -> str:
    return f"""#!/usr/bin/env bash
# Auto-generated by cosmic-cli init --grok — boot canary + temple floor canary, then grok.
set -euo pipefail
export PYTHONPATH={root!r}${{PYTHONPATH:+:$PYTHONPATH}}
COSMIC_PY={py!r}
_cosmic() {{ "${{COSMIC_PY}}" -m cosmic_cli.main "$@"; }}

echo "cosmic-launch-grok: running boot canary…" >&2
if ! _cosmic gate --boot-canary; then
  echo "cosmic-launch-grok: BOOT CANARY FAILED — refuse cockpit launch" >&2
  exit 1
fi

echo "cosmic-launch-grok: running temple floor canary…" >&2
if ! _cosmic gate --floor-canary; then
  echo "cosmic-launch-grok: FLOOR CANARY FAILED — refuse cockpit launch" >&2
  echo "cosmic-launch-grok: re-run: cosmic-cli init --grok --force" >&2
  exit 1
fi

if ! command -v grok >/dev/null 2>&1; then
  [[ -x "${{HOME}}/.grok/bin/grok" ]] && PATH="${{HOME}}/.grok/bin:${{PATH}}"
fi
if ! command -v grok >/dev/null 2>&1; then
  echo "cosmic-launch-grok: grok not on PATH" >&2
  exit 1
fi

# Default install is fail-closed: temple floor always on for this launcher.
export GROK_SANDBOX=temple
echo "cosmic-launch-grok: canaries PASS — exec grok (GROK_SANDBOX=temple)" >&2
exec grok "$@"
"""


def install_grok_hooks(*, force: bool = False) -> Tuple[str, bool]:
    if not _TEMPLATE_SRC.is_file():
        return f"[Error] hook template missing at {_TEMPLATE_SRC}", False

    dest_dir = Path.home() / ".cosmic-cli" / "hooks"
    dest_dir.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(dest_dir, 0o700)
    except OSError:
        pass

    wrapper_dst = dest_dir / "cosmic-gate-wrapper.sh"
    wrapper_dst.write_text(_render_wrapper(), encoding="utf-8")
    wrapper_dst.chmod(wrapper_dst.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    if _WRAPPER_SRC.is_file():
        stock = dest_dir / "cosmic-gate-wrapper.stock.sh"
        shutil.copy2(_WRAPPER_SRC, stock)

    py = sys.executable
    root = str(_PKG_ROOT)
    launcher_dst = dest_dir / "cosmic-launch-grok.sh"
    launcher_dst.write_text(_render_launcher(py, root), encoding="utf-8")
    launcher_dst.chmod(launcher_dst.stat().st_mode | stat.S_IXUSR)

    # Temple kernel floor — provisioned, not example-only
    from cosmic_cli.temple_floor import provision_temple_floor, run_floor_canary

    floor_msg = provision_temple_floor()

    grok_hooks = Path.home() / ".grok" / "hooks"
    grok_hooks.mkdir(parents=True, exist_ok=True)
    json_path = grok_hooks / "cosmic-pretooluse.json"
    if json_path.exists() and not force:
        # Still refresh floor + launcher even when hook JSON kept
        fc = run_floor_canary()
        status = "PASS" if fc == 0 else "FAIL"
        return (
            f"init --grok: wrapper at {wrapper_dst}; hook JSON exists "
            f"({json_path}) — use --force to overwrite; {floor_msg}; "
            f"floor-canary {status}; launch: {launcher_dst}",
            fc == 0,
        )

    template = _TEMPLATE_SRC.read_text(encoding="utf-8")
    body = template.replace("__WRAPPER_PATH__", str(wrapper_dst.resolve()))
    json_path.write_text(body, encoding="utf-8")

    fc = run_floor_canary()
    if fc != 0:
        return (
            f"init --grok partial: hook installed but floor-canary FAILED — "
            f"{floor_msg}. Fix sandbox then re-run init --grok --force.",
            False,
        )

    return (
        f"init --grok ok: wrapper={wrapper_dst} hook={json_path} "
        f"(global PreToolUse); {floor_msg}; floor-canary PASS. "
        f"Launch: {launcher_dst}",
        True,
    )
