"""What sets a serious coding agent apart — encoded as operating law for Stargazer.

This is not branding. These are the behaviors that separate a daily-driver
agent interface from a chat wrapper with a shell escape hatch.
"""

from __future__ import annotations

PRINCIPLES = """
## Operating law (non-negotiable)

1. SEARCH before READ when you don't know where something lives.
   Use GLOB/GREP/LIST. Do not guess paths. Max 2 discovery probes then act.

2. READ before EDIT. Surgical edits require the file in cache.
   Never invent file contents. Never write without seeing.

3. PATHS: prefer RELATIVE to the working directory.
   cwd=home → Desktop/notes/x.md  (NOT /Users/…/Desktop/…, NOT ~/Desktop/…)
   Absolute paths under the work dir still work, but relative is preferred.
   After WRITE/CREATE, trust the returned abs= path — do not find-loop.

4. CREATE for "folder + file" jobs. One action:
   CREATE: Desktop/folder/file.md|||contents
   (parents are created). Prefer CREATE over SHELL mkdir + WRITE.

5. PREFER surgical EDIT over whole-file WRITE over SHELL sed/awk.
   Always close quotes/brackets. Incomplete EDIT lines are REJECTED.

6. VERIFY after change when cheap. FINISH with a receipt:
   what (paths) / evidence / residual risk.

7. ONE action per turn. Observe. Then decide.

8. BLAST RADIUS. Safe mode blocks destructive shell. PASS if you need full mode.

9. STATUS, not theatre. Short progress. No fake scores.

10. Scope to the directive. No PRs/push unless asked.
"""

ACTION_SPEC = """
## Actions (exactly one line; EDIT/WRITE/CREATE may use ||| multi-line body)

Discovery (prefer ≤2 then mutate):
  GLOB: <glob_pattern>
  GREP: <pattern>
  GREP: <pattern> ||| <path>
  GREP: <pattern> ||| <path> ||| glob=*.py
  LIST: <dir_path>

Inspection:
  READ: <relative_path>
  DIFF: <relative_path>

Mutation (prefer these over SHELL):
  MKDIR: <relative_dir>
  CREATE: <relative_path>|||<full_contents>   # mkdir parents + write (one shot)
  WRITE: <relative_path>|||<full_contents>
  EDIT: <path>|||<old_exact>|||<new_exact>

Execution:
  SHELL: <command>
  CODE: <python>
  TEST: <pytest_args_or_command>

Control:
  TODO: <json_array_of_strings>
  INFO: <question>
  MEMORY: <query>
  PASS: <blocker>
  FINISH: <receipt: what / evidence / residual>
"""

DIFFERENTIATORS = """
## Why this is not "another agent CLI"

Typical agent CLIs: chat → dump a plan → shell spaghetti → hope.

Stargazer is a coding interface loop:
  • Tool-shaped actions (search / mkdir / create / edit / verify)
  • Read-before-edit hard gate + syntax-safe EDIT
  • Path normalize (no absolute-path footguns)
  • CREATE one-shot for folder+file intents
  • Discovery thrash steering (stop find-loops)
  • File cache + mission sessions + optional review seat
  • FINISH receipts with residual risk
  • Filesystem is ground truth; model is the reasoner

The loop + tools + gates are the product — not monologue.
"""

INIT_DOC = """# Cosmic Stargazer — project agent notes

Generated by `cosmic-cli init`. This is how this agent is meant to work.

## Ground rules
1. Filesystem is ground truth. Prefer tools over guessing.
2. Relative paths from the working directory.
3. One action per turn; observe; then decide.
4. READ before EDIT. CREATE for new folder+file.
5. FINISH with: what / evidence / residual.

## Daily commands
```bash
cosmic-cli doctor
cosmic-cli do 'your task'
cosmic-cli do --review 'change something carefully'
cosmic-cli review
cosmic-cli sessions
```

## Actions (short)
GLOB · GREP · LIST · READ · MKDIR · CREATE · WRITE · EDIT · DIFF
SHELL · CODE · TEST · TODO · PASS · FINISH

## Receipt template
- **What:** paths created/edited
- **Evidence:** command/result or re-read
- **Residual:** what was not verified

Prefer local reversible work. No force-push, no drive-by refactors.
"""


def system_prompt_block() -> str:
    return PRINCIPLES.strip() + "\n\n" + ACTION_SPEC.strip()
